# Generated by Django 4.0.3 on 2022-03-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='defualt value', max_length=100),
        ),
    ]
